;;; docx-view-test.el --- Tests for docx-view  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Nick

;; Author: Nick <nick@maderightsoftware.com>
;; Assisted-by: Claude Code:claude-opus-5
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is part of docx-view.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Run with:  make test
;;
;; See the Makefile for the batch invocation itself.  It is not repeated here
;; because checkdoc reads the lowercase program name in it as a misspelling of
;; Emacs, and one true finding is worth more than a file that is quiet only
;; because its reader has been told to ignore things.
;;
;; The fixtures under test/fixtures are generated by generate-fixtures.py and
;; are hand-built OOXML, so each one exercises a named feature of the format:
;;
;;   revisions.docx    every revision element Word can emit, including the
;;                     ones pandoc discards
;;   comments.docx     ranged, threaded, resolved, overlapping, point and
;;                     unanchored comments
;;   combined.docx     changes and comments together, CJK, emoji, and every
;;                     character that could collide with org syntax
;;   clean.docx        no revisions and no comments at all
;;   no-extended.docx  comments without word/commentsExtended.xml, as older
;;                     writers produce
;;
;; Tests that need pandoc are skipped rather than failed when it is absent, so
;; the suite still says something useful on a machine without it.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'org-element)
(require 'docx-view)

;;;; Harness

(defconst docx-view-test-directory
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory holding this test file.")

(defun docx-view-test-fixture (name)
  "Return the absolute path of fixture NAME."
  (expand-file-name (format "fixtures/%s.docx" name) docx-view-test-directory))

(defun docx-view-test-contains (needle haystack)
  "Return non-nil when NEEDLE occurs in HAYSTACK as a literal substring.

`string-search' would say this in one call, but it arrived in Emacs 28.1 and
this package supports 27.1.  `string-match-p' is not a substitute on its own:
the strings compared here are document text, carrying regexp characters of
their own -- the fixtures deliberately include \"*bold?*\", \"[link]\" and
\"100%\" -- so the needle is quoted before it is used as a pattern."
  (and (string-match-p (regexp-quote needle) haystack) t))

(defmacro docx-view-test-with-pandoc (&rest body)
  "Run BODY, skipping the test when pandoc is unavailable.

The skip goes through `ert-skip' rather than `skip-unless'.  `skip-unless' is
not a function or a global macro: `ert-deftest' binds it with `cl-macrolet'
around the test body, so it is only visible to code written directly inside a
test.  A macro that expands into it is fine at run time but unresolvable when
this file is byte-compiled -- measured on Emacs 27.1 and 27.2: \"the following
functions are not known to be defined: skip-unless\", which is an error here
because warnings are errors.  `ert-skip' is a plain function, present since
Emacs 26, and does the same thing."
  (declare (indent 0))
  `(progn
     (unless (docx-view-pandoc-available-p)
       (ert-skip "pandoc is not installed"))
     ,@body))

(defmacro docx-view-test-with-copy (name var &rest body)
  "Copy fixture NAME to a temporary file bound to VAR and run BODY.
A copy is used wherever a test could write, so a bug cannot damage the
fixtures themselves.

VAR is bound in a `let' of its own rather than directly to the temporary
name, so that a test with no use for the path can name it `_file' and say so.
Binding it directly would make the copy and the delete count as uses, and the
compiler would then object that an underscore-prefixed variable was not left
unused after all."
  (declare (indent 2))
  (let ((path (gensym "docx-view-test-path")))
    `(let ((,path (make-temp-file "docx-view-test" nil ".docx")))
       (unwind-protect
           (progn (copy-file (docx-view-test-fixture ,name) ,path t)
                  (let ((,var ,path)) ,@body))
         (delete-file ,path)))))

(defmacro docx-view-test-with-buffer (name var &rest body)
  "Open a copy of fixture NAME in `docx-view-mode' and run BODY in it.
VAR is bound to the temporary file's name, and may be underscore-prefixed
when the body has no use for it."
  (declare (indent 2))
  (let ((path (gensym "docx-view-test-path")))
    `(docx-view-test-with-copy ,name ,path
       (let ((buffer (find-file-noselect ,path)))
         (unwind-protect
             (with-current-buffer buffer
               (let ((,var ,path)) ,@body))
           (with-current-buffer buffer
             (set-buffer-modified-p nil)
             (kill-buffer)))))))

(defun docx-view-test-checksum (file)
  "Return the SHA-256 of FILE's bytes."
  (with-temp-buffer
    (set-buffer-multibyte nil)
    (insert-file-contents-literally file)
    (secure-hash 'sha256 (current-buffer))))

(defun docx-view-test-visible-text (text)
  "Return TEXT as org displays it, with the link brackets folded away."
  (with-temp-buffer
    (insert text)
    (goto-char (point-min))
    (while (re-search-forward org-link-bracket-re nil t)
      (replace-match (or (match-string 2) (match-string 1)) t t))
    (buffer-string)))

(defun docx-view-test-body (text)
  "Return the document part of rendered TEXT, without the trailing sections."
  (car (split-string text "^\\*\\* \\(Comments\\|Other revisions\\) (")))

(defun docx-view-test-words (text)
  "Return the words of TEXT with all markup removed.

Used to compare our rendering against pandoc's own plain output.  Only
content is compared: heading stars, our change links and comment markers,
org emphasis characters and both writers' table rules are layout, and the two
writers place them differently by design."
  (with-temp-buffer
    (insert text)
    (goto-char (point-min))
    (while (re-search-forward org-link-bracket-re nil t)
      (replace-match (or (match-string 2) (match-string 1)) t t))
    (goto-char (point-min))
    (while (re-search-forward "(\\([0-9]+\\)[^)]*)" nil t) (replace-match "" t t))
    (goto-char (point-min))
    (while (re-search-forward "^\\*+ \\|\\[fn:[0-9]+\\]\\|[|*/_~=​]" nil t)
      (replace-match " " t t))
    (seq-remove (lambda (w) (or (string-empty-p w) (string-match-p "\\`[-+]+\\'" w)))
                (split-string (buffer-string) "[ \t\n\r\f]+" t))))

(defun docx-view-test-pandoc-plain (file mode)
  "Return pandoc's own plain-text rendering of FILE in MODE."
  (with-temp-buffer
    (call-process (docx-view-pandoc-executable) nil t nil
                  "--from=docx" "--to=plain"
                  (format "--track-changes=%s" mode) file)
    (buffer-string)))

(defun docx-view-test-kind-counts (changes)
  "Return an alist of kind to count over CHANGES."
  (let (acc)
    (dolist (c changes) (cl-incf (alist-get (docx-view-change-kind c) acc 0)))
    acc))

;;;; The pandoc layer

(ert-deftest docx-view-test-pandoc-available ()
  "The pandoc layer reports whether pandoc can be run, and its version."
  (docx-view-test-with-pandoc
    (should (stringp (docx-view-pandoc-executable)))
    (should (file-executable-p (docx-view-pandoc-executable)))
    (let ((version (docx-view-pandoc-version)))
      (should (stringp version))
      (should (string-match-p "\\`[0-9]+\\(\\.[0-9]+\\)*\\'" version))
      ;; The docx reader's tracked-change support needs a modern pandoc.
      (should (>= (string-to-number (car (split-string version "\\."))) 2)))
    ;; The cache is reset on demand, so changing the program takes effect.
    (docx-view-pandoc-reset-version)
    (should (equal (docx-view-pandoc-version) (docx-view-pandoc-version)))))

(ert-deftest docx-view-test-pandoc-ast-shape ()
  "An AST is an alist carrying blocks, meta and the api version."
  (docx-view-test-with-pandoc
    (let ((ast (docx-view-pandoc-ast (docx-view-test-fixture "revisions"))))
      (should (consp ast))
      (should (proper-list-p (docx-view-pandoc-blocks ast)))
      (should (docx-view-pandoc-blocks ast))
      (should (proper-list-p (docx-view-pandoc-api-version ast))))))

(ert-deftest docx-view-test-pandoc-node-accessors ()
  "A tagged node reports its tag, and a ColWidth's float payload is safe.

The float matters: `docx-view-pandoc-children' is called on every node during
a walk, and a ColWidth's payload is a number rather than a list, which raised
a wrong-type-argument before the guard was added."
  (docx-view-test-with-pandoc
    (let* ((ast (docx-view-pandoc-ast (docx-view-test-fixture "revisions")))
           (blocks (docx-view-pandoc-blocks ast))
           (tags nil))
      (letrec ((walk (lambda (n)
                       (cond
                        ((docx-view-pandoc-node-p n)
                         (push (docx-view-pandoc-tag n) tags)
                         ;; must not signal, whatever the payload is
                         (funcall walk (docx-view-pandoc-children n)))
                        ((and (consp n) (proper-list-p n))
                         (mapc walk n))))))
        (funcall walk blocks))
      (should (member "Para" tags))
      (should (member "Span" tags))
      (should (member "Table" tags)))))

(ert-deftest docx-view-test-pandoc-span-kinds ()
  "Revision spans are recognised by their pandoc class."
  (docx-view-test-with-pandoc
    (let ((kinds nil))
      (letrec ((walk (lambda (n)
                       (cond
                        ((docx-view-pandoc-node-p n)
                         (let ((k (docx-view-pandoc-span-kind n)))
                           (when k (push k kinds)))
                         (funcall walk (docx-view-pandoc-children n)))
                        ((and (consp n) (proper-list-p n)) (mapc walk n))))))
        (funcall walk (docx-view-pandoc-blocks
                       (docx-view-pandoc-ast (docx-view-test-fixture "revisions")))))
      (should (memq 'insertion kinds))
      (should (memq 'deletion kinds))
      (should (memq 'paragraph-insertion kinds))
      (should (memq 'paragraph-deletion kinds)))))

(ert-deftest docx-view-test-pandoc-stringify-omits-attributes ()
  "Stringify returns prose, not the author and date of the spans it walks.

A span's attribute triple is one of its children, so a walker that descends
into every child emits the author name and timestamp into the middle of the
text.  This asserts the content index that prevents it."
  (docx-view-test-with-pandoc
    (let ((text (mapconcat
                 (lambda (b) (docx-view-pandoc-stringify b))
                 (docx-view-pandoc-blocks
                  (docx-view-pandoc-ast (docx-view-test-fixture "revisions")))
                 " ")))
      (should-not (string-match-p "Alice Smith" text))
      (should-not (string-match-p "2026-08-01T" text))
      (should (string-match-p "utilise" text)))))

(ert-deftest docx-view-test-pandoc-stringify-omits-comment-bodies ()
  "A comment's text does not leak into the document's prose.
Pandoc puts the whole comment body inside the `comment-start' span, so a
naive walk prints the discussion in the middle of the sentence."
  (docx-view-test-with-pandoc
    (let ((text (mapconcat
                 (lambda (b) (docx-view-pandoc-stringify b))
                 (docx-view-pandoc-blocks
                  (docx-view-pandoc-ast (docx-view-test-fixture "combined")))
                 " ")))
      (should-not (string-match-p "Comment with special chars" text)))))

(ert-deftest docx-view-test-pandoc-filter-all-is-identity ()
  "Filtering in `all' mode returns the very same object, not a copy."
  (docx-view-test-with-pandoc
    (let ((blocks (docx-view-pandoc-blocks
                   (docx-view-pandoc-ast (docx-view-test-fixture "revisions")))))
      (should (eq blocks (docx-view-pandoc-filter-changes blocks 'all))))))

(ert-deftest docx-view-test-pandoc-filter-matches-pandoc ()
  "Accepting and rejecting in Lisp agrees word-for-word with pandoc's own passes.

This is the test that justifies running pandoc once and filtering the tree
three ways, rather than running it three times.  Content is compared, not
layout, per `docx-view-test-words'.

The prose fixtures are used.  revisions.docx is excluded because it holds a
table, a hyperlink and a footnote, where pandoc's plain writer and an org
renderer place markers and rules differently by design; that fixture's
filtering is covered by `docx-view-test-pandoc-filter-moves-text'."
  (docx-view-test-with-pandoc
    (dolist (fixture '("comments" "combined" "clean" "no-extended"))
      (dolist (mode '(accept reject))
        (let* ((file (docx-view-test-fixture fixture))
               (ours (docx-view-test-words
                      (docx-view-test-body
                       (docx-view-document-text
                        (docx-view-render-document file mode)))))
               (theirs (docx-view-test-words
                        (docx-view-test-pandoc-plain file mode))))
          (should (equal ours theirs)))))))

(ert-deftest docx-view-test-pandoc-filter-moves-text ()
  "Accepting keeps every insertion and drops every deletion, and vice versa.

The invariant holds for the fixture with tables, links and footnotes too,
where a word-for-word comparison against pandoc's plain writer would only be
comparing the two writers' layouts."
  (docx-view-test-with-pandoc
    (dolist (fixture '("revisions" "comments" "combined" "no-extended"))
      (let* ((file (docx-view-test-fixture fixture))
             (changes (docx-view-document-changes
                       (docx-view-render-document file 'all)))
             (accepted (docx-view-document-text
                        (docx-view-render-document file 'accept)))
             (rejected (docx-view-document-text
                        (docx-view-render-document file 'reject)))
             (texts (lambda (kind)
                      ;; Short runs are skipped: a one-word insertion may
                      ;; legitimately also occur in untouched prose.
                      (seq-filter
                       (lambda (s) (> (length s) 3))
                       (mapcar (lambda (c) (string-trim (or (docx-view-change-text c) "")))
                               (seq-filter (lambda (c) (eq kind (docx-view-change-kind c)))
                                           changes)))))
             (inserted (funcall texts 'insertion))
             (deleted (funcall texts 'deletion)))
        (should (or inserted deleted))
        (dolist (text inserted)
          (should (docx-view-test-contains text accepted))
          (unless (member text deleted)
            (should-not (docx-view-test-contains text rejected))))
        (dolist (text deleted)
          (should (docx-view-test-contains text rejected))
          (unless (member text inserted)
            (should-not (docx-view-test-contains text accepted))))))))

(ert-deftest docx-view-test-pandoc-filter-collapses-spaces ()
  "Dropping a change does not leave the spaces that surrounded it doubled.

Word writes the spaces around a revision as runs of their own, so
\"<ins>clearly</ins> <del>somewhat</del> shows\" arrives as Span, Space,
Span, Space, Str.  Measured: pandoc's docx reader never emits two adjacent
Space nodes itself, in any mode, on any fixture -- so a run of two after
filtering is our own doing, and reads as \"clearly  shows\"."
  (docx-view-test-with-pandoc
    (cl-labels ((longest-run (nodes)
                  (let ((worst 0) (run 0))
                    (dolist (node nodes)
                      (if (and (docx-view-pandoc-node-p node)
                               (member (docx-view-pandoc-tag node)
                                       '("Space" "SoftBreak")))
                          (setq run (1+ run) worst (max worst run))
                        (setq run 0)
                        (cond
                         ((docx-view-pandoc-node-p node)
                          (setq worst (max worst (longest-run
                                                  (docx-view-pandoc-children node)))))
                         ((and (consp node) (proper-list-p node))
                          (setq worst (max worst (longest-run node)))))))
                    worst)))
      (dolist (fixture '("revisions" "comments" "combined" "clean" "no-extended"))
        (let ((blocks (docx-view-pandoc-blocks
                       (docx-view-pandoc-ast (docx-view-test-fixture fixture)))))
          (dolist (mode '(all accept reject))
            (should (<= (longest-run (docx-view-pandoc-filter-changes blocks mode))
                        1)))))
      ;; And no doubled space reaches the rendered prose.
      (dolist (mode '(accept reject))
        (should-not
         (string-match-p
          "[^ \n]  [^ \n]"
          (docx-view-test-visible-text
           (docx-view-document-text
            (docx-view-render-document (docx-view-test-fixture "combined") mode)))))))))

;;;; The OOXML layer

(ert-deftest docx-view-test-ooxml-comments ()
  "Every comment in the part is read, with author, date and body."
  (let ((comments (docx-view-ooxml-comments (docx-view-test-fixture "comments"))))
    (should (= 11 (length comments)))
    (dolist (c comments)
      (should (stringp (docx-view-comment-id c)))
      (should (docx-view-comment-paragraphs c)))
    (should (member "Alice Smith" (mapcar #'docx-view-comment-author comments)))))

(ert-deftest docx-view-test-ooxml-threading ()
  "Replies are nested under the comment they answer.
Threading lives in word/commentsExtended.xml, which pandoc does not read at
all, so this information exists only because the OOXML layer recovers it."
  (let* ((comments (docx-view-ooxml-comments (docx-view-test-fixture "comments")))
         (threads (docx-view-ooxml-comment-threads comments)))
    ;; Fewer threads than comments means at least one reply was attached.
    (should (< (length threads) (length comments)))
    (should (cl-some (lambda (thread) (> (length thread) 1)) threads))
    ;; Every comment appears exactly once across all threads.
    (should (= (length comments)
               (apply #'+ (mapcar #'length threads))))))

(ert-deftest docx-view-test-ooxml-resolved-and-unanchored ()
  "Resolved threads and comments anchored nowhere are both identified."
  (let ((comments (docx-view-ooxml-comments (docx-view-test-fixture "comments"))))
    (should (cl-some #'docx-view-comment-resolved comments))
    (should (cl-some (lambda (c) (not (docx-view-comment-anchored c))) comments))))

(ert-deftest docx-view-test-ooxml-missing-extended-part ()
  "A document with no commentsExtended.xml still yields its comments.
Older writers omit the part; treating its absence as an error would make the
viewer useless on those files."
  (let ((file (docx-view-test-fixture "no-extended")))
    (should-not (docx-view-ooxml-part-exists-p file "word/commentsExtended.xml"))
    (let ((comments (docx-view-ooxml-comments file)))
      (should (= 1 (length comments)))
      (should-not (docx-view-comment-resolved (car comments))))))

(ert-deftest docx-view-test-ooxml-extra-revisions ()
  "The revisions pandoc discards are recovered from the XML."
  (let* ((extra (docx-view-ooxml-extra-revisions
                 (docx-view-test-fixture "revisions")))
         (kinds (mapcar #'docx-view-extra-revision-kind extra)))
    (should (= 10 (length extra)))
    (dolist (kind '(move-from move-to run-format paragraph-format
                              cell-insert cell-delete row-insert row-delete))
      (should (memq kind kinds)))
    ;; A move's name identifies which move it belongs to, and lives on the
    ;; range-start element rather than on the content.
    (should (cl-some (lambda (r) (and (memq (docx-view-extra-revision-kind r)
                                            '(move-from move-to))
                                      (docx-view-extra-revision-name r)))
                     extra))))

(ert-deftest docx-view-test-ooxml-clean-document ()
  "A document with nothing tracked yields no comments and no revisions."
  (let ((file (docx-view-test-fixture "clean")))
    (should (null (docx-view-ooxml-comments file)))
    (should (null (docx-view-ooxml-extra-revisions file)))))

(ert-deftest docx-view-test-ooxml-rejects-non-archive ()
  "A file that is not a zip is reported as such, not read as an empty document.

The distinction matters because a document with no comments and a document
that cannot be opened at all would otherwise both arrive as nil, and the
second would be shown to the user as the first."
  (let ((file (make-temp-file "docx-view-test" nil ".docx")))
    (unwind-protect
        (progn
          (with-temp-file file (insert "definitely not a zip\n"))
          (should-error (docx-view-ooxml--part-names file)
                        :type 'docx-view-bad-archive)
          (should-error (docx-view-ooxml-comments file)
                        :type 'docx-view-bad-archive)
          (should-error (docx-view-ooxml-extra-revisions file)
                        :type 'docx-view-bad-archive))
      (delete-file file))))

(ert-deftest docx-view-test-ooxml-part-exists-p ()
  "Archive membership is reported for a part that is present and one that is not."
  (let ((file (docx-view-test-fixture "comments")))
    (should (docx-view-ooxml-part-exists-p file "word/document.xml"))
    (should (docx-view-ooxml-part-exists-p file "word/comments.xml"))
    (should-not (docx-view-ooxml-part-exists-p file "word/nothing-here.xml"))
    ;; An absent part parses to nil rather than signalling, because most
    ;; documents legitimately lack the optional comment parts.
    (should-not (docx-view-ooxml-parse-part file "word/nothing-here.xml"))
    (should (docx-view-ooxml-parse-part file "word/document.xml"))))

;;;; Rendering

(ert-deftest docx-view-test-render-counts ()
  "Each fixture produces the changes, comments and revisions it contains."
  (docx-view-test-with-pandoc
    (pcase-dolist (`(,fixture ,changes ,comments ,extra)
                   '(("revisions" 21 0 10)
                     ("comments" 11 11 0)
                     ("combined" 7 1 0)
                     ("clean" 0 0 0)
                     ("no-extended" 2 1 0)))
      (let ((doc (docx-view-render-document (docx-view-test-fixture fixture) 'all)))
        (should (= changes (length (docx-view-document-changes doc))))
        (should (= comments (length (docx-view-document-comments doc))))
        (should (= extra (length (docx-view-document-extra doc))))))))

(ert-deftest docx-view-test-render-kinds ()
  "Insertions, deletions and paragraph marks are each rendered as such."
  (docx-view-test-with-pandoc
    (let* ((doc (docx-view-render-document (docx-view-test-fixture "revisions") 'all))
           (counts (docx-view-test-kind-counts (docx-view-document-changes doc))))
      (should (= 10 (alist-get 'insertion counts)))
      (should (= 7 (alist-get 'deletion counts)))
      (should (= 2 (alist-get 'paragraph-insertion counts)))
      (should (= 2 (alist-get 'paragraph-deletion counts))))))

(ert-deftest docx-view-test-render-authors-and-dates ()
  "Every reviewer is named, in the order they first appear."
  (docx-view-test-with-pandoc
    (let ((doc (docx-view-render-document (docx-view-test-fixture "revisions") 'all)))
      (should (equal '("Alice Smith" "Bob Jones" "Carol White")
                     (docx-view-document-authors doc)))
      (dolist (change (docx-view-document-changes doc))
        (when (docx-view-change-date change)
          ;; A date must format to something other than the raw timestamp.
          (should-not (string-match-p
                       "T" (docx-view-render-format-date
                            (docx-view-change-date change)))))))))

(ert-deftest docx-view-test-render-modes-differ ()
  "Accepting and rejecting produce different text, and both differ from `all'."
  (docx-view-test-with-pandoc
    (let* ((file (docx-view-test-fixture "combined"))
           (all (docx-view-document-text (docx-view-render-document file 'all)))
           (yes (docx-view-document-text (docx-view-render-document file 'accept)))
           (no (docx-view-document-text (docx-view-render-document file 'reject))))
      (should-not (equal all yes))
      (should-not (equal yes no))
      ;; Accepting keeps inserted text and drops deleted text.
      (should (string-match-p "这是插入的内容" (docx-view-test-visible-text yes)))
      (should-not (string-match-p "这是插入的内容" (docx-view-test-visible-text no)))
      (should (string-match-p "这是删除的内容" (docx-view-test-visible-text no)))
      (should-not (string-match-p "这是删除的内容" (docx-view-test-visible-text yes)))
      ;; Only `all' still carries the change links.
      (should (string-match-p docx-view-render-link-type all))
      (dolist (text (list yes no))
        (should-not (string-match-p
                     (rx (literal docx-view-render-link-type) ":ins-")
                     text))))))

(ert-deftest docx-view-test-render-parses-as-org ()
  "The rendered text is valid org: links, headings, tables and footnotes."
  (docx-view-test-with-pandoc
    (dolist (fixture '("revisions" "comments" "combined" "clean" "no-extended"))
      (let* ((doc (docx-view-render-document (docx-view-test-fixture fixture) 'all))
             (changes (docx-view-document-changes doc)))
        (with-temp-buffer
          (let ((org-inhibit-startup t)) (org-mode))
          (insert (docx-view-document-text doc))
          (let* ((tree (org-element-parse-buffer))
                 (links (org-element-map tree 'link
                          (lambda (l)
                            (when (equal (org-element-property :type l)
                                         docx-view-render-link-type)
                              (org-element-property :path l))))))
            ;; Every change must be findable as a real org link of our type.
            (dolist (change changes)
              (should (member (docx-view-change-key change) links)))
            ;; Every table row must have the same number of columns.
            (dolist (table (org-element-map tree 'table #'identity))
              (let ((widths (org-element-map table 'table-row
                              (lambda (row)
                                (when (eq (org-element-property :type row) 'standard)
                                  (length (org-element-map row 'table-cell
                                            #'identity)))))))
                (should (= 1 (length (delete-dups (copy-sequence widths)))))))))))))

(ert-deftest docx-view-test-render-guards-org-structure ()
  "Document text that starts a line with org syntax is not read as syntax."
  (dolist (text '("* not a heading" "| not a table" "- not a bullet"
                  "1. not a list" "#+not a keyword" ": not fixed width"
                  "+ not a bullet either"))
    (let ((guarded (docx-view-render-guard-line text)))
      (should-not (equal guarded text))
      (with-temp-buffer
        (let ((org-inhibit-startup t)) (org-mode))
        (insert guarded "\n")
        (let ((tree (org-element-parse-buffer)))
          (should-not (org-element-map tree '(headline table item) #'identity))))))
  ;; Ordinary prose is left exactly as it was.
  (dolist (text '("plain prose" "a * mid-line star" "not | a table"))
    (should (equal text (docx-view-render-guard-line text)))))

(ert-deftest docx-view-test-render-guard-is-invisible ()
  "The guard character takes up no space on screen."
  (should (= 0 (string-width docx-view-render--zwsp)))
  (should (= (string-width "* text")
             (string-width (docx-view-render-guard-line "* text")))))

(ert-deftest docx-view-test-render-nested-changes ()
  "A comment anchored inside an insertion yields sibling links, not nested ones.
Org links cannot nest, so the outer marking is split into a run of links that
share one key."
  (docx-view-test-with-pandoc
    (let* ((doc (docx-view-render-document (docx-view-test-fixture "comments") 'all))
           (text (docx-view-document-text doc)))
      ;; No link description may itself open a link.
      (should-not (string-match-p
                   (rx "[[" (literal docx-view-render-link-type) ":"
                       (* (not (any "]"))) "]["
                       (* (not (any "]"))) "[[")
                   text))
      ;; And the text still parses, with every key present.
      (with-temp-buffer
        (let ((org-inhibit-startup t)) (org-mode))
        (insert text)
        (let ((links (org-element-map (org-element-parse-buffer) 'link
                       (lambda (l)
                         (when (equal (org-element-property :type l)
                                      docx-view-render-link-type)
                           (org-element-property :path l))))))
          (dolist (change (docx-view-document-changes doc))
            (should (member (docx-view-change-key change) links))))))))

(ert-deftest docx-view-test-render-comment-numbers-agree ()
  "An inline marker's number is the number the comment section gives it."
  (docx-view-test-with-pandoc
    (let* ((doc (docx-view-render-document (docx-view-test-fixture "comments") 'all))
           (visible (docx-view-test-visible-text (docx-view-document-text doc))))
      ;; Markers are (N) and the section lists [N]; both are derived from the
      ;; document's own comment order, so each marker must have an entry.
      (let ((markers nil) (entries nil) (pos 0))
        (while (string-match "(\\([0-9]+\\)[^)]*)" visible pos)
          (push (string-to-number (match-string 1 visible)) markers)
          (setq pos (match-end 0)))
        (setq pos 0)
        (while (string-match "^ *- \\[\\([0-9]+\\)\\] " visible pos)
          (push (string-to-number (match-string 1 visible)) entries)
          (setq pos (match-end 0)))
        (should entries)
        (dolist (marker markers)
          (should (memq marker entries)))))))

(ert-deftest docx-view-test-render-comment-section-structure ()
  "The comment section reports threading, resolution and anchoring."
  (docx-view-test-with-pandoc
    (let ((visible (docx-view-test-visible-text
                    (docx-view-document-text
                     (docx-view-render-document
                      (docx-view-test-fixture "comments") 'all)))))
      (should (string-match-p "^\\*\\* Comments (11)$" visible))
      (should (string-match-p "(resolved)" visible))
      (should (string-match-p "(unanchored)" visible))
      ;; A reply is indented under its parent.
      (should (string-match-p "^  - \\[" visible)))))

(ert-deftest docx-view-test-render-extra-section ()
  "Revisions pandoc discards are listed, in plain language."
  (docx-view-test-with-pandoc
    (let ((visible (docx-view-test-visible-text
                    (docx-view-document-text
                     (docx-view-render-document
                      (docx-view-test-fixture "revisions") 'all)))))
      (should (string-match-p "^\\*\\* Other revisions (10)$" visible))
      (should (string-match-p "table row inserted" visible))
      (should (string-match-p "moved to here" visible))
      (should (string-match-p "character formatting changed" visible)))))

(ert-deftest docx-view-test-render-footnotes ()
  "A footnote's body is kept, not dropped.
Pandoc's Note payload is a list of one element -- the block list -- so
rendering its first child instead of the whole payload loses the body."
  (docx-view-test-with-pandoc
    (let* ((doc (docx-view-render-document (docx-view-test-fixture "revisions") 'all))
           (text (docx-view-document-text doc)))
      (should (string-match-p "\\[fn:1\\]" text))
      (with-temp-buffer
        (let ((org-inhibit-startup t)) (org-mode))
        (insert text)
        (let* ((tree (org-element-parse-buffer))
               (defs (org-element-map tree 'footnote-definition #'identity)))
          (should defs)
          (dolist (def defs)
            (should (org-element-contents def))))))))

(ert-deftest docx-view-test-render-preserves-unicode ()
  "CJK text, emoji and org's own special characters all survive."
  (docx-view-test-with-pandoc
    (let ((visible (docx-view-test-visible-text
                    (docx-view-document-text
                     (docx-view-render-document
                      (docx-view-test-fixture "combined") 'all)))))
      (should (string-match-p "这是插入的内容" visible))
      (should (string-match-p "αβγ" visible))
      (should (string-match-p "😀" visible))
      (should (string-match-p "a & b <tag>" visible))
      (should (string-match-p "\\[brackets\\]" visible)))))

(ert-deftest docx-view-test-render-clean-document ()
  "A document with nothing tracked renders as plain prose."
  (docx-view-test-with-pandoc
    (let ((doc (docx-view-render-document (docx-view-test-fixture "clean") 'all)))
      (should (null (docx-view-document-changes doc)))
      (should (null (docx-view-document-warnings doc)))
      (should-not (string-match-p docx-view-render-link-type
                                  (docx-view-document-text doc)))
      (should-not (string-match-p "Comments (" (docx-view-document-text doc)))
      (should-not (string-match-p "Other revisions ("
                                  (docx-view-document-text doc))))))

(ert-deftest docx-view-test-render-warns-about-unanchored ()
  "The reader says when a comment is anchored nowhere in the text."
  (docx-view-test-with-pandoc
    (let ((doc (docx-view-render-document (docx-view-test-fixture "comments") 'all)))
      (should (docx-view-document-warnings doc))
      (should (cl-some (lambda (w) (string-match-p "anchored nowhere" w))
                       (docx-view-document-warnings doc))))))

(ert-deftest docx-view-test-render-date-formatting ()
  "A UTC date is shown in local time, and an unparsable one is passed through.

Displaying local time is the point: a reviewer wants to know when a comment
was written in their own frame of reference, not in whichever zone the author
happened to be in.  So the expected string has to be computed rather than
written down.  Writing it down is what broke this test: \"2026-08-01 03:00\"
is right at UTC-7 and wrong everywhere else, so it passed on its author's
machine and failed on CI, which runs at UTC.  Measured, same input:
03:00 at America/Los_Angeles, 10:00 at UTC, 19:00 at Asia/Tokyo.

`format-time-string' is given the same instant and left to apply the same
zone, so the assertion holds in any zone while still failing if the parsing,
the field selection or the format string regresses."
  (let* ((instant (encode-time (decoded-time-set-defaults
                                (parse-time-string "2026-08-01T10:00:00Z"))))
         (expected (format-time-string "%Y-%m-%d %H:%M" instant))
         (formatted (docx-view-render-format-date "2026-08-01T10:00:00Z")))
    (should (equal expected formatted))
    ;; The shape must hold in any zone.  Minutes are not asserted to be "00":
    ;; not every offset is a whole number of hours.  Measured on the same
    ;; instant: 15:30 at Asia/Kolkata, 15:45 at Asia/Kathmandu, 18:45 at
    ;; Australia/Eucla.  An earlier version of this test required ":00" and so
    ;; failed for roughly a fifth of the world.
    (should (string-match-p "\\`[0-9]\\{4\\}-[01][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]\\'"
                            formatted))
    ;; The instant itself is what must not drift: parsing and re-formatting
    ;; must land back on 10:00 UTC whatever the local zone does to the display.
    (should (equal "2026-08-01 10:00"
                   (format-time-string "%Y-%m-%d %H:%M" instant t))))
  (should (equal "not a date" (docx-view-render-format-date "not a date")))
  ;; A date with no time at all still formats, since the defaults fill it in.
  (should (docx-view-render-format-date "2026-08-01T00:00:00Z")))

;;;; Locating changes

(ert-deftest docx-view-test-locate-changes ()
  "Every change is found in the buffer, and its bounds cover its own text."
  (docx-view-test-with-pandoc
    (dolist (fixture '("revisions" "comments" "combined" "no-extended"))
      (let* ((doc (docx-view-render-document (docx-view-test-fixture fixture) 'all))
             (changes (docx-view-document-changes doc)))
        (with-temp-buffer
          (let ((org-inhibit-startup t)) (org-mode))
          (insert (docx-view-document-text doc))
          (should (null (docx-view-render-locate-changes changes)))
          (dolist (change changes)
            (should (docx-view-change-beg change))
            (should (docx-view-change-end change))
            (should (<= (docx-view-change-beg change)
                        (docx-view-change-end change)))))))))

;;;; Org compatibility

(ert-deftest docx-view-test-show-all-works-across-org-versions ()
  "Unfolding works whichever of org's two names for it exists.

Org 9.6 renamed `org-show-all' to `org-fold-show-all'.  Emacs 27 and 28 are
inside this package's supported range and bundle org 9.5, which has only the
old name, so naming the new one directly does not compile there.  Verified
against org 9.5.5 from org's own git: `org-fold-show-all' is absent, and the
buffer still unfolds through the old name."
  (with-temp-buffer
    (let ((org-inhibit-startup t)) (org-mode))
    (insert "* one\ntext under one\n* two\ntext under two\n")
    (org-overview)
    (goto-char (point-min))
    ;; That something is hidden is the assertion, not what it is called.  Org
    ;; has two folding implementations and they use different property values:
    ;; measured on the same buffer, `outline' under `org-fold-core-style' set
    ;; to `overlays' and `org-fold-outline' under `text-properties'.  An
    ;; earlier version of this test required `outline' and so failed on the
    ;; versions defaulting to the other style.
    (should (get-char-property (line-end-position) 'invisible))
    (docx-view--show-all)
    (goto-char (point-min))
    (should-not (get-char-property (line-end-position) 'invisible))
    ;; Nothing anywhere is left hidden.
    (should-not (text-property-not-all (point-min) (point-max) 'invisible nil))))

(ert-deftest docx-view-test-callable-rejects-a-dangling-alias ()
  "`docx-view--callable' answers for what can really be called.

An obsolete alias whose target has been removed still satisfies `fboundp'
while signalling `void-function' when called, so `fboundp' alone would pick a
name that does not work.  This matters because org keeps `org-show-all' as an
alias for `org-fold-show-all' on every modern Emacs."
  (should (eq 'ignore (docx-view--callable "ignore")))
  (should-not (docx-view--callable "docx-view-test-no-such-function"))
  ;; A symbol that exists as a variable but not as a function.
  (should-not (docx-view--callable "docx-view-startup-folded"))
  ;; An alias pointing at nothing: fboundp says yes, calling it fails.
  (let ((alias (make-symbol "docx-view-test-dangling")))
    (fset alias (make-symbol "docx-view-test-absent-target"))
    (should (fboundp alias))
    (should-error (funcall alias) :type 'void-function)))

;;;; The major mode

(ert-deftest docx-view-test-mode-renders-on-open ()
  "Opening a .docx gives a rendered org buffer that still visits the file."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" file
      (should (eq major-mode 'docx-view-mode))
      (should (derived-mode-p 'org-mode))
      (should (equal file buffer-file-name))
      (should buffer-read-only)
      (should-not (buffer-modified-p))
      (should enable-multibyte-characters)
      (should docx-view--document)
      (should (= 21 (length (docx-view-document-changes docx-view--document))))
      (should (= 21 (length docx-view--overlays))))))

(ert-deftest docx-view-test-mode-refuses-to-save ()
  "Saving cannot overwrite the document.

This is the test that matters most, because the failure it guards against
destroys a user's document.  Measured on a copy of a real .docx: with no
guard, and with `buffer-read-only' set but no write hook, `save-buffer'
writes the rendered org text over the .docx and its checksum changes.
Read-only stops typing, not saving.

The route walked here is the one a user actually takes: \\[read-only-mode] to
make the view writable, an edit, then \\[save-buffer].  Saving an unmodified buffer is not a
test of anything -- `save-buffer' returns without running a single write
hook, so it passes whether the guard is present or not."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "comments" file
      (let ((before (docx-view-test-checksum file)))
        (should-not (buffer-modified-p))
        (read-only-mode -1)
        (goto-char (point-max))
        (insert "an edit that must never reach the file\n")
        (should (buffer-modified-p))
        (should-error (save-buffer) :type 'user-error)
        (should (equal before (docx-view-test-checksum file)))
        ;; And again, in case the hook is consumed by the first attempt.
        (should-error (save-buffer) :type 'user-error)
        (should (equal before (docx-view-test-checksum file)))
        (set-buffer-modified-p nil)))))

(ert-deftest docx-view-test-mode-refuses-write-file ()
  "Writing the buffer under the document's own name is refused too."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "comments" file
      (let ((before (docx-view-test-checksum file)))
        (should-error (write-file file) :type 'user-error)
        (should (equal before (docx-view-test-checksum file)))))))

(ert-deftest docx-view-test-mode-refuses-to-clobber-another-docx ()
  "Writing under a second document's name leaves that document alone.

The protection also has to survive the attempt.  `write-file' calls
`set-visited-file-name' before any write hook runs, and that clears
`backup-inhibited' and recomputes the auto-save name -- measured, and it left
a #doc.docx# of org text on disk.  So the state after the refusal is asserted,
not just the refusal itself."
  (docx-view-test-with-pandoc
    (docx-view-test-with-copy "revisions" victim
      (docx-view-test-with-buffer "comments" _file
        (let ((before (docx-view-test-checksum victim)))
          (should-error (write-file victim) :type 'user-error)
          (should (equal before (docx-view-test-checksum victim)))
          ;; Still a protected view of a document, despite the new name.
          (should (memq 'docx-view--refuse-write write-contents-functions))
          (should-not buffer-auto-save-file-name)
          (should backup-inhibited)
          (should docx-view--file)
          ;; And a second attempt is refused as well.
          (should-error (save-buffer) :type 'user-error)
          (should (equal before (docx-view-test-checksum victim))))))))

(ert-deftest docx-view-test-mode-allows-write-file-to-a-non-document ()
  "Saving the rendered text under a name that is not a document is allowed.

Refusing this would make the view a trap: the text could be read but never
kept.  Only .docx targets are refused, because only those would put org text
where a zip archive belongs.  Once the buffer visits an ordinary file it is an
ordinary buffer, and saving it again has to work."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "comments" file
      (let ((before (docx-view-test-checksum file))
            (out (make-temp-file "docx-view-test-out" nil ".org")))
        (unwind-protect
            (progn
              (write-file out)
              (should (file-exists-p out))
              (should (string-prefix-p
                       "#+title:"
                       (with-temp-buffer (insert-file-contents out)
                                         (buffer-string))))
              ;; The document it came from is untouched.
              (should (equal before (docx-view-test-checksum file)))
              ;; And protection has been dropped, since there is nothing left
              ;; to protect.
              (should-not (memq 'docx-view--refuse-write write-contents-functions))
              (should-not docx-view--file)
              (let ((inhibit-read-only t))
                (goto-char (point-max))
                (insert "an ordinary edit\n"))
              (save-buffer)
              (should-not (buffer-modified-p)))
          (when (file-exists-p out) (delete-file out)))))))

(ert-deftest docx-view-test-mode-survives-a-major-mode-change ()
  "A major mode change cannot strip the write guard.

This is the most serious bug the suite has caught, and it destroyed a
document.  `write-contents-functions' is not `permanent-local', so the
`kill-all-local-variables' that every major mode change performs removed the
guard.  Measured, before the fix: open a document, \\`M-x text-mode',
\\[save-buffer], and the .docx had been overwritten with org text -- its
checksum changed and its first bytes read \"#+title:\".

`buffer-read-only', `backup-inhibited' and the auto-save name are plain
locals, so the mode change clears those too; they are restored from
`after-change-major-mode-hook'.  All of it is asserted here, because each one
alone is enough to put org text on disk beside the document."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "comments" file
      (let ((before (docx-view-test-checksum file)))
        (text-mode)
        (should (eq major-mode 'text-mode))
        (should (memq 'docx-view--refuse-write write-contents-functions))
        (should buffer-read-only)
        (should backup-inhibited)
        (should-not buffer-auto-save-file-name)
        (should docx-view--file)
        (let ((inhibit-read-only t))
          (goto-char (point-max))
          (insert "text that must never reach the document\n"))
        (should-error (save-buffer) :type 'user-error)
        (should (equal before (docx-view-test-checksum file)))
        (set-buffer-modified-p nil)))))

(ert-deftest docx-view-test-mode-survives-repeated-mode-changes ()
  "Several mode changes in a row neither strip the guard nor duplicate it."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "clean" file
      (let ((before (docx-view-test-checksum file)))
        (fundamental-mode)
        (prog-mode)
        (text-mode)
        (should (= 1 (cl-count 'docx-view--refuse-write write-contents-functions)))
        (should (= 1 (cl-count 'docx-view--reprotect-buffer
                               after-change-major-mode-hook)))
        (let ((inhibit-read-only t)) (goto-char (point-max)) (insert "x\n"))
        (should-error (save-buffer) :type 'user-error)
        (should (equal before (docx-view-test-checksum file)))
        (set-buffer-modified-p nil)))))

(ert-deftest docx-view-test-protection-does-not-leak-to-other-buffers ()
  "An unrelated file is not made unsavable by docx-view having been used.

The guard is permanent, which is what makes it survive a mode change, so it
is worth proving it is also confined: a buffer that never showed a document
must save normally."
  (let ((file (make-temp-file "docx-view-test-plain" nil ".txt")))
    (unwind-protect
        (progn
          (with-temp-file file (insert "ordinary text\n"))
          (let ((buffer (find-file-noselect file)))
            (unwind-protect
                (with-current-buffer buffer
                  (should-not (memq 'docx-view--refuse-write
                                    write-contents-functions))
                  (should-not docx-view--file)
                  (goto-char (point-max))
                  (insert "an edit\n")
                  (save-buffer)
                  (should-not (buffer-modified-p)))
              (with-current-buffer buffer
                (set-buffer-modified-p nil)
                (kill-buffer)))))
      (delete-file file))))

(ert-deftest docx-view-test-mode-no-auto-save-or-backup ()
  "No auto-save file and no backup are made of a generated buffer."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "clean" _file
      (should-not buffer-auto-save-file-name)
      (should backup-inhibited)
      (should-not buffer-offer-save))))

(ert-deftest docx-view-test-document-name-p ()
  "The name test used by the write guard answers for a nonexistent file.

`docx-view-file-p' reads the file's leading bytes, so it cannot answer for a
\\[write-file] target that does not exist yet.  That is the whole reason this
second predicate exists, so the distinction is asserted rather than assumed."
  (should (docx-view-document-name-p "/nowhere/at/all/report.docx"))
  (should (docx-view-document-name-p "/nowhere/report.docm"))
  (should (docx-view-document-name-p "/nowhere/template.dotx"))
  (should-not (docx-view-document-name-p "/nowhere/notes.org"))
  (should-not (docx-view-document-name-p "/nowhere/report.docx.bak"))
  (should-not (docx-view-document-name-p nil))
  ;; The contents test disagrees on a nonexistent file, which is the point.
  (should-not (docx-view-file-p "/nowhere/at/all/report.docx")))

(ert-deftest docx-view-test-mode-leaves-other-files-alone ()
  "Entering the mode on something that is not a document erases nothing.

The mode replaces the buffer's contents, so invoked by mistake on an org
file it would otherwise throw the file's text away."
  (let ((file (make-temp-file "docx-view-test" nil ".org")))
    (unwind-protect
        (progn
          (with-temp-file file (insert "* notes worth keeping\nsecond line\n"))
          (let ((buffer (find-file-noselect file)))
            (unwind-protect
                (with-current-buffer buffer
                  (docx-view-mode)
                  (should (string-match-p "notes worth keeping" (buffer-string)))
                  (should-not buffer-read-only)
                  (should-not docx-view--document))
              (with-current-buffer buffer
                (set-buffer-modified-p nil)
                (kill-buffer)))))
      (delete-file file))))

(ert-deftest docx-view-test-file-p ()
  "The archive probe accepts documents and rejects everything else."
  (should (docx-view-file-p (docx-view-test-fixture "clean")))
  (should-not (docx-view-file-p "/nonexistent/nowhere.docx"))
  (should-not (docx-view-file-p temporary-file-directory))
  (let ((file (make-temp-file "docx-view-test" nil ".docx")))
    (unwind-protect
        (progn
          (with-temp-file file (insert "plain text\n"))
          (should-not (docx-view-file-p file)))
      (delete-file file))))

(ert-deftest docx-view-test-mode-reports-a-broken-document ()
  "An unreadable document produces an explanation, not a backtrace."
  (let ((file (make-temp-file "docx-view-test" nil ".docx")))
    (unwind-protect
        (progn
          ;; A valid empty zip: the probe accepts it, pandoc will not.
          (with-temp-file file
            (set-buffer-multibyte nil)
            (insert "PK\5\6" (make-string 18 0)))
          (let ((buffer (find-file-noselect file)))
            (unwind-protect
                (with-current-buffer buffer
                  (should (eq major-mode 'docx-view-mode))
                  (should (string-match-p "could not be read" (buffer-string)))
                  (should-not (buffer-modified-p)))
              (with-current-buffer buffer
                (set-buffer-modified-p nil)
                (kill-buffer)))))
      (delete-file file))))

(ert-deftest docx-view-test-mode-switching ()
  "Cycling the view mode re-renders, and the file stays read-only throughout."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "combined" file
      (let ((before (docx-view-test-checksum file))
            (texts nil))
        (dolist (mode '(all accept reject))
          (docx-view-set-mode mode)
          (should (eq docx-view--mode mode))
          (should buffer-read-only)
          (should-not (buffer-modified-p))
          (push (buffer-string) texts))
        (should (= 3 (length (delete-dups texts))))
        (should (equal before (docx-view-test-checksum file)))))))

(ert-deftest docx-view-test-mode-cycle-wraps ()
  "Cycling visits all three modes and returns to the first."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "combined" _file
      (should (eq 'all docx-view--mode))
      (docx-view-cycle-mode)
      (should (eq 'accept docx-view--mode))
      (docx-view-cycle-mode)
      (should (eq 'reject docx-view--mode))
      (docx-view-cycle-mode)
      (should (eq 'all docx-view--mode)))))

(ert-deftest docx-view-test-mode-rejects-unknown-mode ()
  "An unknown view mode is refused in plain language."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "clean" _file
      (should-error (docx-view-set-mode 'sideways) :type 'user-error))))

(ert-deftest docx-view-test-link-type-is-registered ()
  "The change link type is registered with org at load time.

Without registration org parses \"[[dvchg:ins-1][very]]\" as a fuzzy link
whose path is the whole string.  The buffer still looks right, so the failure
is invisible: it is every query for our links that comes back empty."
  (should (member docx-view-render-link-type (org-link-types)))
  (should (eq #'docx-view-change-face
              (org-link-get-parameter docx-view-render-link-type :face)))
  (should (org-link-get-parameter docx-view-render-link-type :follow)))

(ert-deftest docx-view-test-change-faces ()
  "A change's face reflects its kind and its author."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (dolist (change (docx-view-document-changes docx-view--document))
        (let ((face (docx-view-change-face (docx-view-change-key change))))
          (should face)
          (pcase (docx-view-change-kind change)
            ('insertion (should (member 'docx-view-insertion (flatten-tree face))))
            ('deletion (should (member 'docx-view-deletion (flatten-tree face)))))))
      ;; Authors get distinct colours.
      (let ((authors (docx-view-document-authors docx-view--document)))
        (should (= (length authors)
                   (length (delete-dups
                            (mapcar (lambda (a)
                                      (docx-view-render-author-color a authors))
                                    authors)))))))))

(ert-deftest docx-view-test-change-at-point ()
  "The change at a position is identifiable from the buffer alone."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (dolist (change (docx-view-document-changes docx-view--document))
        (goto-char (docx-view-change-beg change))
        (should (equal (docx-view-change-key change) (docx-view-change-at-point)))
        (should (eq change (docx-view-change-by-key (docx-view-change-at-point))))
        (should (docx-view-change-help nil nil (point)))))))

(ert-deftest docx-view-test-navigation ()
  "Moving forward and back visits every change, and stops at the ends."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (goto-char (point-min))
      (let ((seen nil))
        (dotimes (_ 40)
          (ignore-errors (docx-view-next-change 1))
          (let ((key (docx-view-change-at-point)))
            (when key (cl-pushnew key seen :test #'equal))))
        ;; Every change with a distinct starting position is reachable.
        (should (>= (length seen) 15)))
      ;; And backwards from the end.
      (goto-char (point-max))
      (docx-view-previous-change 1)
      (should (docx-view-change-at-point))
      ;; Past the last change, the command says so rather than erring.
      (goto-char (point-max))
      (should (docx-view-next-change 1)))))

(ert-deftest docx-view-test-change-list ()
  "The change list has one line per change and can jump to each."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (let ((source (current-buffer))
            (changes (docx-view-document-changes docx-view--document)))
        (docx-view-list-changes)
        (unwind-protect
            (with-current-buffer "*docx-view changes*"
              (should (eq major-mode 'docx-view-list-mode))
              (should (eq source docx-view-list--source))
              (should (= (length changes)
                         (count-lines (point-min) (point-max))))
              (goto-char (point-min))
              (should (get-text-property (point) 'docx-view-key)))
          (kill-buffer "*docx-view changes*"))))))

(ert-deftest docx-view-test-change-list-when-clean ()
  "A document with no changes says so rather than showing an empty list."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "clean" _file
      (docx-view-list-changes)
      (unwind-protect
          (with-current-buffer "*docx-view changes*"
            (should (string-match-p "no tracked changes" (buffer-string))))
        (kill-buffer "*docx-view changes*")))))

(ert-deftest docx-view-test-author-filter ()
  "Filtering by author dims the others without removing them."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (let* ((authors (docx-view-document-authors docx-view--document))
             (chosen (car authors))
             (size (buffer-size)))
        (docx-view-filter-author chosen)
        (should (equal chosen docx-view--author-filter))
        (should (= size (buffer-size)))
        ;; Another author's changes are shadowed, the chosen one's are not.
        (dolist (change (docx-view-document-changes docx-view--document))
          (let ((face (docx-view-change-face (docx-view-change-key change))))
            (if (equal chosen (docx-view-change-author change))
                (should-not (eq face 'shadow))
              (when (docx-view-change-author change)
                (should (eq face 'shadow))))))
        (docx-view-filter-author "")
        (should-not docx-view--author-filter)))))

(ert-deftest docx-view-test-revert ()
  "Reverting re-renders rather than reinstating the document's bytes."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "comments" file
      (let ((before (buffer-string))
            (checksum (docx-view-test-checksum file))
            (revert-without-query (list ".*")))
        (revert-buffer t t)
        (should (eq major-mode 'docx-view-mode))
        (should (equal before (buffer-string)))
        (should buffer-read-only)
        (should (equal checksum (docx-view-test-checksum file)))))))

(ert-deftest docx-view-test-commands-after-leaving-the-mode ()
  "A command run in a buffer that is no longer a view reports it plainly."
  (with-temp-buffer
    (should-error (docx-view-set-mode 'accept) :type 'user-error)
    (should-error (docx-view-next-change 1) :type 'user-error)
    (should-error (docx-view-list-changes) :type 'user-error)
    (should-error (docx-view-revert) :type 'user-error)))

(ert-deftest docx-view-test-imenu ()
  "The imenu index offers the document's headings and its changes."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (let ((index (docx-view--imenu-index)))
        (should (assoc "Headings" index))
        (should (assoc "Changes" index))
        (should (cdr (assoc "Headings" index)))
        (should (= (length (docx-view-document-changes docx-view--document))
                   (length (cdr (assoc "Changes" index)))))))))

(ert-deftest docx-view-test-header-line ()
  "The summary heading counts changes, comments and unshown revisions."
  (docx-view-test-with-pandoc
    (docx-view-test-with-buffer "revisions" _file
      (let ((line (docx-view--header-line docx-view--document)))
        (should (string-match-p "21 changes" line))
        (should (string-match-p "0 comments" line))
        (should (string-match-p "10 unshown revisions" line))))
    (docx-view-test-with-buffer "no-extended" _file
      (let ((line (docx-view--header-line docx-view--document)))
        ;; Singular and plural are both handled.
        (should (string-match-p "1 change," line))
        (should (string-match-p "1 comment" line))))))

(ert-deftest docx-view-test-file-name-regexp ()
  "The mode is offered for documents and templates alike."
  (dolist (name '("a.docx" "a.docm" "a.dotx" "a.dotm"))
    (should (string-match-p docx-view-file-name-regexp name))
    (should (eq 'docx-view-mode
                (assoc-default name auto-mode-alist #'string-match))))
  (dolist (name '("a.doc" "a.odt" "a.org" "a.docx.bak"))
    (should-not (string-match-p docx-view-file-name-regexp name))))

(ert-deftest docx-view-test-external-open-needs-a-file ()
  "Opening externally is refused when there is no document."
  (with-temp-buffer
    (should-error (docx-view-open-externally) :type 'user-error)))

(ert-deftest docx-view-test-autoload-cookies ()
  "Everything a fresh install reaches before loading the file is autoloaded.

This is the one class of bug the rest of the suite cannot see.  Every other
test has already loaded docx-view, so every symbol resolves whether it is
autoloaded or not.  A real installation has loaded nothing: package.el has
only the generated autoloads file, and if the `auto-mode-alist' entry names a
mode that is not in it, Emacs reports \"Ignoring unknown mode\" and leaves the
raw zip archive in `fundamental-mode'.  That was measured, not imagined.

So the cookies are asserted against the source text.  Reading the file is the
only way to check them, because by the time this runs the definitions are
loaded and indistinguishable from autoloaded ones."
  (let ((source (expand-file-name "../docx-view.el" docx-view-test-directory)))
    (should (file-readable-p source))
    (with-temp-buffer
      (insert-file-contents source)
      (dolist (form '("(define-derived-mode docx-view-mode org-mode"
                      "(defun docx-view-find-file "
                      "(defalias 'docx-view "
                      "(defconst docx-view-file-name-regexp"
                      "(add-to-list 'auto-mode-alist"
                      "(add-to-list 'auto-coding-alist"
                      "(defun docx-view-dired-view "))
        (goto-char (point-min))
        (should (search-forward form nil t))
        ;; The cookie must be on the line before the form, which is what
        ;; `loaddefs-generate' looks for.
        (forward-line -1)
        (should (looking-at-p "^;;;###autoload$"))))))

(provide 'docx-view-test)

;;; docx-view-test.el ends here
